//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiochVolunteer.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiochVolunteer.Resources.Strings.GenericStrings", typeof(GenericStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill.
        /// </summary>
        public static string ADD_SKILL {
            get {
                return ResourceManager.GetString("ADD_SKILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to scheduling.
        /// </summary>
        public static string ADD_TO_SCHEDULING {
            get {
                return ResourceManager.GetString("ADD_TO_SCHEDULING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can this job be preformed by anyone?.
        /// </summary>
        public static string CAN_BE_PREFORMED_BY_ANYONE {
            get {
                return ResourceManager.GetString("CAN_BE_PREFORMED_BY_ANYONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        public static string CLEAR_SELECTION {
            get {
                return ResourceManager.GetString("CLEAR_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select jobs that can be done in conjunction with this one..
        /// </summary>
        public static string COMBO_JOBS_MESSAGE {
            get {
                return ResourceManager.GetString("COMBO_JOBS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Event.
        /// </summary>
        public static string CREATE_NEW_EVENT {
            get {
                return ResourceManager.GetString("CREATE_NEW_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Job.
        /// </summary>
        public static string CREATE_NEW_JOB {
            get {
                return ResourceManager.GetString("CREATE_NEW_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Schedule.
        /// </summary>
        public static string CREATE_NEW_SCHEDULE {
            get {
                return ResourceManager.GetString("CREATE_NEW_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Volunteer.
        /// </summary>
        public static string CREATE_NEW_VOLUNTEER {
            get {
                return ResourceManager.GetString("CREATE_NEW_VOLUNTEER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details View.
        /// </summary>
        public static string DETAILS_VIEW {
            get {
                return ResourceManager.GetString("DETAILS_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the event.
        /// </summary>
        public static string EVENT_DATE {
            get {
                return ResourceManager.GetString("EVENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string EVENTS {
            get {
                return ResourceManager.GetString("EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select jobs that will be preformed at event..
        /// </summary>
        public static string EVENTS_JOBS_MESSAGE {
            get {
                return ResourceManager.GetString("EVENTS_JOBS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FIRST_NAME {
            get {
                return ResourceManager.GetString("FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string JOBS {
            get {
                return ResourceManager.GetString("JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LAST_NAME {
            get {
                return ResourceManager.GetString("LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;-.
        /// </summary>
        public static string LEFT_ARROW {
            get {
                return ResourceManager.GetString("LEFT_ARROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of Volunteers for this job.
        /// </summary>
        public static string MIN_VOL_MESSAGE {
            get {
                return ResourceManager.GetString("MIN_VOL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended number of Volunteers for this job.
        /// </summary>
        public static string REC_VOL_MESSAGE {
            get {
                return ResourceManager.GetString("REC_VOL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&gt;.
        /// </summary>
        public static string RIGHT_ARROW {
            get {
                return ResourceManager.GetString("RIGHT_ARROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string SCHEDULE {
            get {
                return ResourceManager.GetString("SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SELECT_ALL {
            get {
                return ResourceManager.GetString("SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select skills sets from below.
        /// </summary>
        public static string SELECT_SKILL_SETS {
            get {
                return ResourceManager.GetString("SELECT_SKILL_SETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string SKILLS {
            get {
                return ResourceManager.GetString("SKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this a recurring event?.
        /// </summary>
        public static string TEMPLATE_MESSAGE {
            get {
                return ResourceManager.GetString("TEMPLATE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the same volunteer list for all listed events..
        /// </summary>
        public static string USE_SAME_VOLS {
            get {
                return ResourceManager.GetString("USE_SAME_VOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Events.
        /// </summary>
        public static string VIEW_EVENTS {
            get {
                return ResourceManager.GetString("VIEW_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Jobs.
        /// </summary>
        public static string VIEW_JOBS {
            get {
                return ResourceManager.GetString("VIEW_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Schedules.
        /// </summary>
        public static string VIEW_SCHEDULE {
            get {
                return ResourceManager.GetString("VIEW_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Volunteers.
        /// </summary>
        public static string VIEW_VOLUNTEERS {
            get {
                return ResourceManager.GetString("VIEW_VOLUNTEERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers.
        /// </summary>
        public static string VOLUNTEERS {
            get {
                return ResourceManager.GetString("VOLUNTEERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
